//
//  AdDetailInteractorTests.swift
//  iOSCodeChallenge
//
//  Created by Borja Saez de Guinoa Vilaplana on 20/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import iOSCodeChallenge
import XCTest
//
//class AdDetailInteractorTests: XCTestCase
//{
//  // MARK: Subject under test
//  
//  var sut: AdDetailInteractor!
//  
//  // MARK: Test lifecycle
//  
//  override func setUp()
//  {
//    super.setUp()
//    setupAdDetailInteractor()
//  }
//  
//  override func tearDown()
//  {
//    super.tearDown()
//  }
//  
//  // MARK: Test setup
//  
//  func setupAdDetailInteractor()
//  {
//    sut = AdDetailInteractor()
//  }
//  
//  // MARK: Test doubles
//  
//  class AdDetailPresentationLogicSpy: AdDetailPresentationLogic
//  {
//    var presentSomethingCalled = false
//    
//    func presentSomething(response: AdDetail.Something.Response)
//    {
//      presentSomethingCalled = true
//    }
//  }
//  
//  // MARK: Tests
//  
//  func testDoSomething()
//  {
//    // Given
//    let spy = AdDetailPresentationLogicSpy()
//    sut.presenter = spy
//    let request = AdDetail.Something.Request()
//    
//    // When
//    sut.doSomething(request: request)
//    
//    // Then
//    XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
//  }
//}
