//
//  AdDetailPresenterTests.swift
//  iOSCodeChallenge
//
//  Created by Borja Saez de Guinoa Vilaplana on 20/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import iOSCodeChallenge
import XCTest

//class AdDetailPresenterTests: XCTestCase
//{
//  // MARK: Subject under test
//  
//  var sut: AdDetailPresenter!
//  
//  // MARK: Test lifecycle
//  
//  override func setUp()
//  {
//    super.setUp()
//    setupAdDetailPresenter()
//  }
//  
//  override func tearDown()
//  {
//    super.tearDown()
//  }
//  
//  // MARK: Test setup
//  
//  func setupAdDetailPresenter()
//  {
//    sut = AdDetailPresenter()
//  }
//  
//  // MARK: Test doubles
//  
//  class AdDetailDisplayLogicSpy: AdDetailDisplayLogic
//  {
//    var displaySomethingCalled = false
//    
//    func displaySomething(viewModel: AdDetail.Something.ViewModel)
//    {
//      displaySomethingCalled = true
//    }
//  }
//  
//  // MARK: Tests
//  
//  func testPresentSomething()
//  {
//    // Given
//    let spy = AdDetailDisplayLogicSpy()
//    sut.viewController = spy
//    let response = AdDetail.Something.Response()
//    
//    // When
//    sut.presentSomething(response: response)
//    
//    // Then
//    XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
//  }
//}
