//
//  AdDetailPresenter.swift
//  iOSCodeChallenge
//
//  Created by Borja Saez de Guinoa Vilaplana on 13/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AdDetailPresentationLogic
{
  func presentSomething(response: AdDetail.Something.Response)
}

class AdDetailPresenter: AdDetailPresentationLogic
{
  weak var viewController: AdDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: AdDetail.Something.Response)
  {
    let viewModel = AdDetail.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
