//
//  AdDetailInteractor.swift
//  iOSCodeChallenge
//
//  Created by Borja Saez de Guinoa Vilaplana on 13/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AdDetailBusinessLogic
{
  func doSomething(request: AdDetail.Something.Request)
}

protocol AdDetailDataStore
{
  //var name: String { get set }
}

class AdDetailInteractor: AdDetailBusinessLogic, AdDetailDataStore
{
  var presenter: AdDetailPresentationLogic?
  var worker: AdDetailWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: AdDetail.Something.Request)
  {
    worker = AdDetailWorker()
    worker?.doSomeWork()
    
    let response = AdDetail.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
