//
//  AdDetailModels.swift
//  iOSCodeChallenge
//
//  Created by Borja Saez de Guinoa Vilaplana on 13/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct AdDetailViewModel {
    
    let description: String
    let imagesCells: [CollectionDrawerItemProtocol]
    var price: String = ""
    let isFavorite: Bool
    let property: Property?
    let transaction: TransactionTipology?
    
    
    init(idDetailDTO: IDDetailDTO, isFavorite: Bool){
        self.description = idDetailDTO.propertyComment ?? ""
        
        //create cellModels for images
        let images = idDetailDTO.multimedia?.images.map({$0.url ?? ""}) ?? []
        self.imagesCells = images.map({AdImageCollectionCellModel.init(url: $0)})
        self.property = Property.init(rawValue: idDetailDTO.extendedPropertyType ?? "")
        self.transaction = TransactionTipology.init(rawValue: idDetailDTO.operation ?? "")
        
        if let safePrice = idDetailDTO.price {
            self.price = "\(safePrice)€"
            if transaction == .rent {
                self.price.append(Literals.Common.priceMonth)
            }
        }
        
        self.isFavorite = isFavorite
    }
    
    
    
}
