//
//  AdDetailInteractor.swift
//  iOSCodeChallenge
//
//  Created by Borja Saez de Guinoa Vilaplana on 13/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AdDetailBusinessLogic
{
    func fetchAdDetail()
}

protocol AdDetailDataStore
{
    var detailURL: String { get set }
}

class AdDetailInteractor: AdDetailBusinessLogic, AdDetailDataStore
{
    
    var detailURL: String = ""
    var presenter: AdDetailPresentationLogic?
    var adService: AdServiceProtocol?
    
    init(adService: AdServiceProtocol = AdService()){
        self.adService = adService
    }

    func fetchAdDetail() {
        adService?.fetchAdDetail(adURL: detailURL, success: { [weak self] (detailDTO) in
            self?.presenter?.presentAdDetail(IDDetailDTO: detailDTO)
        }, failure: { [weak self] (error) in
            self?.presenter?.presentError()
        })
    }
}
