//
//  AdDetailModels.swift
//  iOSCodeChallenge
//
//  Created by Borja Saez de Guinoa Vilaplana on 13/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct AdDetailViewModel {
    
    let description: String
    let imagesCells: [CollectionDrawerItemProtocol]
    let price: String
    let isFavorite: Bool
    let property: Property?
    
    
    init(idDetailDTO: IDDetailDTO, isFavorite: Bool){
        self.description = idDetailDTO.propertyComment ?? ""
        
        //create cellModels for images
        let images = idDetailDTO.multimedia?.images.map({$0.url ?? ""}) ?? []
        self.imagesCells = images.map({AdImageCollectionCellModel.init(url: $0)})
        
        if let safePrice = idDetailDTO.price {
            self.price = "\(safePrice)€"
        }else {
            self.price = ""
        }
        self.isFavorite = isFavorite
        self.property = Property.init(rawValue: idDetailDTO.extendedPropertyType ?? "")
    }
    
    
    
}
