//
//  FavoriteAdsListPresenterTests.swift
//  iOSCodeChallenge
//
//  Created by Borja Saez de Guinoa Vilaplana on 20/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import iOSCodeChallenge
import XCTest

//class FavoriteAdsListPresenterTests: XCTestCase
//{
//  // MARK: Subject under test
//  
//  var sut: FavoriteAdsListPresenter!
//  
//  // MARK: Test lifecycle
//  
//  override func setUp()
//  {
//    super.setUp()
//    setupFavoriteAdsListPresenter()
//  }
//  
//  override func tearDown()
//  {
//    super.tearDown()
//  }
//  
//  // MARK: Test setup
//  
//  func setupFavoriteAdsListPresenter()
//  {
//    sut = FavoriteAdsListPresenter()
//  }
//  
//  // MARK: Test doubles
//  
//  class FavoriteAdsListDisplayLogicSpy: FavoriteAdsListDisplayLogic
//  {
//
//  }
//  
//  // MARK: Tests
//  
//  func testPresentSomething()
//  {
//    // Given
//    let spy = FavoriteAdsListDisplayLogicSpy()
//    sut.viewController = spy
//    let response = FavoriteAdsList.Something.Response()
//    
//    // When
//    sut.presentSomething(response: response)
//    
//    // Then
//    XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
//  }
//}
