//
//  AdListInteractorTests.swift
//  iOSCodeChallenge
//
//  Created by Borja Saez de Guinoa Vilaplana on 20/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import iOSCodeChallenge
import XCTest

//class AdListInteractorTests: XCTestCase
//{
//  // MARK: Subject under test
//  
//  var sut: AdListInteractor!
//  
//  // MARK: Test lifecycle
//  
//  override func setUp()
//  {
//    super.setUp()
//    setupAdListInteractor()
//  }
//  
//  override func tearDown()
//  {
//    super.tearDown()
//  }
//  
//  // MARK: Test setup
//  
//  func setupAdListInteractor()
//  {
//    sut = AdListInteractor()
//  }
//  
//  // MARK: Test doubles
//  
//  class AdListPresentationLogicSpy: AdListPresentationLogic
//  {
//    var presentSomethingCalled = false
//    
//    func presentSomething(response: AdList.Something.Response)
//    {
//      presentSomethingCalled = true
//    }
//  }
//  
//  // MARK: Tests
//  
//  func testDoSomething()
//  {
//    // Given
//    let spy = AdListPresentationLogicSpy()
//    sut.presenter = spy
//    let request = AdList.Something.Request()
//    
//    // When
//    sut.doSomething(request: request)
//    
//    // Then
//    XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
//  }
//}
