//
//  AdListViewControllerTests.swift
//  iOSCodeChallenge
//
//  Created by Borja Saez de Guinoa Vilaplana on 20/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import iOSCodeChallenge
import XCTest

class AdListViewControllerTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: AdListViewController!
  var window: UIWindow!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    window = UIWindow()
    setupAdListViewController()
  }
  
  override func tearDown()
  {
    window = nil
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupAdListViewController()
  {
    
    sut = AdListViewController()
  }
  
  func loadView()
  {
    window.addSubview(sut.view)
    RunLoop.current.run(until: Date())
  }
  
  // MARK: Test doubles
  
  class AdListBusinessLogicSpy: AdListBusinessLogic
  {
    var fetchRealStateAdsCalled = false
    var toggleFavoriteStatusCalled = false
    
    func fetchRealStateAds(){
        fetchRealStateAdsCalled = true
    }
    
    func toggleFavoriteStatus(index: Int){
        toggleFavoriteStatusCalled = true
    }
  }
  
  // MARK: Tests
  
  func testShouldDoSomethingWhenViewIsLoaded()
  {
    // Given
    let spy = AdListBusinessLogicSpy()
    sut.interactor = spy
    
    // When
    loadView()
    
    // Then
    XCTAssertTrue(spy.fetchRealStateAdsCalled, "viewDidLoad() should ask the interactor to fetch the list of ads")
  }
  
  func testDisplaySomething()
  {
    // Given
 //   let viewModel = AdList.Something.ViewModel()
    
    // When
//    loadView()
//    sut.displaySomething(viewModel: viewModel)
//
    // Then
    //XCTAssertEqual(sut.nameTextField.text, "", "displaySomething(viewModel:) should update the name text field")
  }
}
