//
//  FavoriteAdsListBuilder.swift
//  iOSCodeChallenge
//
//  Created by Borja Saez de Guinoa Vilaplana on 13/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class FavoriteAdsListBuilder {

    class func viewController() -> FavoriteAdsListViewController {

        let viewController = FavoriteAdsListViewController()
        // connecting all components together
        let interactor = FavoriteAdsListInteractor()
        let presenter = FavoriteAdsListPresenter()
        let router = FavoriteAdsListRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor

        return viewController
    }
}
