//
//  FavoriteAdsListRouter.swift
//  iOSCodeChallenge
//
//  Created by Borja Saez de Guinoa Vilaplana on 13/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FavoriteAdsListRoutingLogic
{
    func navigateToAdDetail(adIndex: Int)
}

protocol FavoriteAdsListDataPassing
{
    var dataStore: FavoriteAdsListDataStore? { get }
    func passDataToAdDetail(index: Int, source: FavoriteAdsListDataStore, destination: inout AdDetailDataStore)
}

class FavoriteAdsListRouter: NSObject, FavoriteAdsListRoutingLogic, FavoriteAdsListDataPassing
{
    
    weak var viewController: FavoriteAdsListViewController?
    var dataStore: FavoriteAdsListDataStore?
    
    func navigateToAdDetail(adIndex: Int) {
        let adDetailVC = AdDetailBuilder.viewController()
        if var adDetailDS = adDetailVC.router?.dataStore, let adListDataStore = dataStore {
            passDataToAdDetail(index: adIndex, source: adListDataStore, destination: &adDetailDS)
        }
        viewController?.navigationController?.pushViewController(adDetailVC, animated: true)
    }
    
    func passDataToAdDetail(index: Int, source: FavoriteAdsListDataStore, destination: inout AdDetailDataStore) {
        destination.idResultDTO = source.favoriteAds[index]
    }
    
}


//@objc protocol AdListRoutingLogic
//{
//    func navigateToAdDetail(adIndex: Int)
//}
//
//protocol AdListDataPassing
//{
//    var dataStore: AdListDataStore? { get }
//
//    func passDataToAdDetail(index: Int, source: AdListDataStore, destination: inout AdDetailDataStore)
//}
//
//class AdListRouter: NSObject, AdListRoutingLogic, AdListDataPassing
//{
//
//    weak var viewController: AdListViewController?
//    var dataStore: AdListDataStore?
//
//
//    func navigateToAdDetail(adIndex: Int) {
//        let adDetailVC = AdDetailBuilder.viewController()
//        if var adDetailDS = adDetailVC.router?.dataStore, let adListDataStore = dataStore {
//            passDataToAdDetail(index: adIndex, source: adListDataStore, destination: &adDetailDS)
//        }
//        viewController?.navigationController?.pushViewController(adDetailVC, animated: true)
//    }
//
//    func passDataToAdDetail(index: Int, source: AdListDataStore, destination: inout AdDetailDataStore) {
//        destination.idResultDTO = source.realStateAdsResults[index]
//    }
//
//}
