//
//  FavoriteAdsListViewController.swift
//  iOSCodeChallenge
//
//  Created by Borja Saez de Guinoa Vilaplana on 13/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoriteAdsListDisplayLogic: class
{
  func displaySomething(viewModel: FavoriteAdsList.Something.ViewModel)
}

class FavoriteAdsListViewController: UITableViewController, FavoriteAdsListDisplayLogic
{
  var interactor: FavoriteAdsListBusinessLogic?
  var router: (NSObjectProtocol & FavoriteAdsListRoutingLogic & FavoriteAdsListDataPassing)?

  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    self.title = Literals.Favorites.title
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = FavoriteAdsList.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: FavoriteAdsList.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
